### PR TITLE
Added antialiasing to notch, correct dimensions, fixed notification panel gap, etc

### PR DESCRIPTION
**Pull request by yankarinRG**
🚫 kang

### CODE REVIEW

**Comment by markakash** [comment]
Hey, thanks for your contribution. I will test those commits, if everything is fine, I will merge it😁

**Comment by yankarinRG** [comment]
Thank you, can't wait! If you want further explanation on the numbers or if you want to tweak them, let me know and I will double-check everything! I want the best for my and our Mi 9! 😊

**Comment by markakash** [comment]
> Thank you, can't wait! If you want further explanation on the numbers or if you want to tweak them, let me know and I will double-check everything! I want the best for my and our Mi 9! 😊
> 
> I can't, for the life of me, find **rounded_corner_radius**, **rounded_corner_radius_top** or **rounded_corner_radius_bottom** (they aren't there, or they're 0) in the original MIUI files. How did you manage to come with 100 and 110 px?

Well, I decompiled frameworks-res and those values are there.

**Comment by yankarinRG** [comment]
Really? Haven't found it looking inside framework-res.apk. What's the name of the dimens? It's not **rounded_corner_radius(_*)**, right?

**Pull request closed without merging**
