### PR TITLE
Round display support, display cutout, fingerprint scanner location, assistant button, corrected resources files, cleanup...

### PR DESCRIPTION
**Pull request by yankarinRG**
🚫 kang

### CODE REVIEW

**Comment by markakash** [comment]
Thanks for the PR: I will review those changes and then merge

**Comment by yankarinRG** [comment]
You're welcome :)

**Comment by yankarinRG** [comment]
@markakash, could you tell me the resource name used in the stock Mi 9 MIUI overlay for _rounded_corner_radius_top_ of 100px and _rounded_corner_radius_bottom_ of 110px? Thanks :)

**Comment by yankarinRG** [comment]
Hello @markakash , any news regarding this PR?

**Comment by yankarinRG** [comment]
@markakash no news yet?

**Comment by yankarinRG** [comment]
@markakash are you alright? It's not very nice to ignore for a month to be honest :)

**Comment by markakash** [comment]
> @markakash are you alright? It's not very nice to ignore for a month to be honest :)

Yo, sorry for the delay and so. I switched to OSS vendor so different tree. This tree is kinda useless now. So, I will close the PR. Thanks for ur time

**Comment by yankarinRG** [comment]
Okay, can you please link the new device tree so I can check if it's all okay and eventually make fixes?

**Pull request closed without merging**
